"use client";

import { Navbar } from "@/components/layout/Navbar";
import { Footer } from "@/components/layout/Footer";

export default function TermsPage() {
    return (
        <div className="min-h-screen bg-white">
            <Navbar />

            <main className="pt-32 pb-20 px-6">
                <div className="mx-auto max-w-3xl">
                    <h1 className="text-4xl font-bold tracking-tight text-gray-900 mb-8">Terms of Service</h1>
                    <p className="text-sm text-gray-500 mb-12">Last updated: December 21, 2025</p>

                    <div className="space-y-8 text-gray-600">
                        <section>
                            <h2 className="text-xl font-bold text-gray-900 mb-4">1. Acceptance of Terms</h2>
                            <p>By accessing or using the SeTutor platform, you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use our services.</p>
                        </section>

                        <section>
                            <h2 className="text-xl font-bold text-gray-900 mb-4">2. User Account</h2>
                            <p>To access certain features of the platform, you may be required to create an account. You are responsible for maintaining the confidentiality of your account information and for all activities that occure under your account.</p>
                        </section>

                        <section>
                            <h2 className="text-xl font-bold text-gray-900 mb-4">3. Intellectual Property</h2>
                            <p>The content generated by SeTutor's AI, including flashcards and summaries, is intended for your personal educational use. SeTutor retains all rights to the underlying technology and algorithms.</p>
                        </section>

                        <section>
                            <h2 className="text-xl font-bold text-gray-900 mb-4">4. Limitation of Liability</h2>
                            <p>SeTutor is an educational aid and does not guarantee specific exam results. We are not liable for any academic outcomes resulting from the use of our platform.</p>
                        </section>
                    </div>
                </div>
            </main>

            <Footer />
        </div>
    );
}
